development: &non_production_settings
  site_name: JukeMan
  username: admin
  password: password
  domain: 10.69.69.101
  
test:
  <<: *non_production_settings
  
production:
  site_name: JukeMan
  username: admin
  password: password
  domain: somewhere.net