development: &non_production_settings
  site_name: JukeMan
  username: admin
  password: password
  
test:
  <<: *non_production_settings
  
production:
  site_name: JukeMan
  username: admin
  password: password