development: &non_production_settings
  site_name: JukeMan
  username: admin
  password: password
  location: Jon's House
  jukeman_server: 10.10.10.1:3000
  import_folder_path: /path/to/music
  
test:
  <<: *non_production_settings
  
production:
  site_name: JukeMan
  username: admin
  password: password
  location: Jon's House
  jukeman_server: 10.10.10.1:3000
  import_folder_path: /path/to/music